#!/bin/sh

#
# THIS FILE IS UNDER PUPPET CONTROL. DON'T EDIT IT HERE.
# USE: git clone git+ssh://$USER@puppet.debian.org/srv/puppet.debian.org/git/dsa-puppet.git
#

set -e

rsync -az --delete geodnssync@dns.debian.org:zonefiles/ /etc/bind/geodns/zonefiles/
sudo /usr/sbin/service bind9 reload
