#!/bin/bash

##
## THIS FILE IS UNDER PUPPET CONTROL. DON'T EDIT IT HERE.
## USE: git clone git+ssh://$USER@puppet.debian.org/srv/puppet.debian.org/git/dsa-puppet.git
##

# by weasel

set -e

[ "$CHROOT_PROFILE" = "dsa" ] || exit 0

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"

if [ -f "${CHROOT_SCRIPT_CONFIG:-}" ]; then
    . "$CHROOT_SCRIPT_CONFIG"
elif [ -f "$CHROOT_PROFILE_DIR/config" ]; then
    . "$CHROOT_PROFILE_DIR/config"
else
    fatal "Cannot find config script"
fi


if [ "$1" = "setup-start" ] || [ "$1" = "setup-recover" ]; then
  SRCL="${CHROOT_PATH}/etc/apt/sources.list.d/auto.list"
  rm -f "$SRCL"
  mirror=${MIRROR:-http://cdn.debian.net/debian}

  case "${SUITE_BASE:-}" in
    experimental)
      echo "deb     $mirror sid main" >> "$SRCL"
      echo "deb-src $mirror sid main" >> "$SRCL"
      ;;
    sid|jessie)
      ;;
    *)
      echo "deb     http://security.debian.org/ ${SUITE_BASE}/updates main" >> "$SRCL"
      echo "deb-src http://security.debian.org/ ${SUITE_BASE}/updates main" >> "$SRCL"
      ;;
  esac
  echo "deb     $mirror ${SUITE_BASE} main" >> "$SRCL"
  echo "deb-src $mirror ${SUITE_BASE} main" >> "$SRCL"

  case "${SUITE_VARIANT:-}" in
    backports)
      case "${SUITE_BASE:-}" in
        squeeze)
          echo "deb     http://backports.debian.org/debian-backports/ ${SUITE_BASE}-${SUITE_VARIANT} main" >> "$SRCL"
          echo "deb-src http://backports.debian.org/debian-backports/ ${SUITE_BASE}-${SUITE_VARIANT} main" >> "$SRCL"
          ;;
        *)
          echo "deb     $mirror ${SUITE_BASE}-${SUITE_VARIANT} main" >> "$SRCL"
          echo "deb-src $mirror ${SUITE_BASE}-${SUITE_VARIANT} main" >> "$SRCL"
          ;;
      esac
      ;;
  esac
  echo "o To install build dependencies run"
  echo "  dd-schroot-cmd -c ${SESSION_ID} apt-get update"
  echo "  followed by build-dep/install as appropriate in the host system."
  echo "o If you started this session with schroot -b, please do not forget to run"
  echo "  schroot --end-session -c ${SESSION_ID}"
  echo "  when you no longer need this environment."
fi
