#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

[ -e /usr/lib/nagios/plugins/dsa-check-timedatectl ] || exit

/usr/lib/nagios/plugins/dsa-check-timedatectl -s >/dev/null 2>/dev/null
rc=$?

case "$rc" in
  1|2)
    pid=$(pgrep -u ntp ntpd)
    if [ -z "$pid" ]; then
      service ntp restart
      exit
    fi

    age=$(ps -ho etimes "$pid")
    if [ "$age" -gt 3600 ]; then
      service ntp restart
    fi
    ;;
  *)
    ;;
esac
