# ~/.bashrc: executed by bash(1) for non-login shells.

## THIS FILE IS UNDER PUPPET CONTROL.
## LOCAL CHANGES WILL BE OVERWRITTEN.

if [ "$PS1" ]; then
  typeset HISTCONTROL=ignoreboth

  export LS_OPTIONS='--color=auto'
  eval "`dircolors`"
  alias ls='ls $LS_OPTIONS'
  alias ll='ls $LS_OPTIONS -l'
  alias l='ls $LS_OPTIONS -lA'
fi

# vim: set ft=sh ts=2 sw=2 et ai si:
