---
nameinfo:
  abel.debian.org: Carl Friedrich Abel (1723 - 1787)
  agnesi.debian.org: Maria Teresa Agnesi (October 17th, 1720 - January 19th, 1795)
  agricola.debian.org: Alexander Agricola (1445 or 1446 - August 15th, 1506)
  alain.debian.org: Jehan Alain (1911 - 1940)
  albeniz.debian.org: Isaac Manuel Francisco Albéniz i Pascual (May 29th, 1860 - May 18th, 1909)
  alwyn.debian.org: William Alwyn (1905 - 1985)
  ancina.debian.org: Giovanni Giovenale Ancina (October 19th, 1545 - August 30th, 1604)
  antheil.debian.org: George Antheil (1900 - 1959)
  arcadelt.debian.org: Jacques Arcadelt (also Jacob Arcadelt) (?1507 - October 14th, 1568)
  argento.debian.org: Dominick Argento (b. October 27th, 1927)
  arne.debian.org: Thomas Augustine Arne (1710 - 1778)
  arnold.debian.org: Malcolm Henry Arnold (1921 - 2006)
  barber.debian.org: Samuel Barber (March 9th, 1910 - January 23rd, 1981)
  beethoven.debian.org: Ludwig van Beethoven (December 16th, 1770 - March 26th, 1827)
  bellini.debian.org: Vincenzo Salvatore Carmelo Francesco Bellini (November 3rd, 1801 - September 23rd, 1835)
  biber.debian.org: Heinrich Ignaz Franz von Biber (August 12th, 1664 - May 3rd, 1704)
  brahms.debian.org: Johannes Brahms (May 7th, 1833 - April 3rd, 1897)
  busoni.debian.org: Ferruccio Dante Michelangiolo Benvenuto Busoni (April 1st, 1866 - July 27th, 1924)
  byrd.debian.org: William Byrd (1543 - July 4th, 1623)
  chopin.debian.org: Frédéric Chopin (March 1st, 1810 - October 17th, 1849)
  cilea.debian.org: Francesco Cilèa (July 26th, 1866 - November 20th, 1950)
  corelli.debian.org: Arcangelo Corelli (February 17th, 1653 - January 8th, 1713)
  danzi.debian.org: Franz Ignaz Danzi (June 15th, 1763 - April 13th, 1826)
  dijkstra.debian.org: Lowell Dijkstra (b.1952)
  draghi.debian.org: Antonio Draghi (1635 - January 16th, 1700)
  duarte.debian.org: Leonora Duarte (July 28th, 1610 - 1678)
  englund.debian.org: Sven Einar Englund (June 17th, 1916 - June 27th, 1999)
  fano.debian.org: Guido Alberto Fano (March 18th, 1875 - August 14th, 1961)
  fasch.debian.org: Johann Friedrich Fasch (1688 - 1758)
  field.debian.org: John Field (1782 - 1837)
  finzi.debian.org: Gerald Raphael Finzi (July 14th, 1901 - September 27th, 1956)
  franck.debian.org: Melchior Franck (1579 - June 1st, 1639)
  gabrielli.debian.org: Domenico Gabrielli (April 15th, 1651 - July 10th, 1690)
  gluck.debian.org: Christoph Willibald Ritter von Gluck (July 2nd, 1714 - November 15th, 1787)
  goedel.debian.org: Kurt Gödel (April 28th, 1906 - January 14th, 1978)
  goetz.debian.org: Hermann Gustav Goetz (December 7th, 1840 - December 3rd, 1876)
  grieg.debian.org: Edvard Hagerup Grieg (June 15th, 1843 - September 4th, 1907)
  handel.debian.org: Georg Friedrich Händel (February 23rd, 1685 - April 14th, 1759)
  heininen.debian.org: Paavo Heininen (January 13th, 1938)
  holter.debian.org: Iver Holter (December 13th, 1850 - January 27th, 1941)
  kassia.debian.org: Kassia (between 805 and 810 - bef. 867)
  kaufmann.debian.org: Georg Friedrich Kauffmann (February 14th, 1679 - February 27th, 1735)
  klecker.debian.org: Dedicated to Joel 'Espy' Klecker (1979 - July 11th, 2000)
  kokkonen.debian.org: Joonas Kokkonen (November 13th, 1921 - October 1st, 1996)
  krenek.debian.org: Ernst Krenek (August 23rd, 1900 - December 22nd, 1991)
  lamb.debian.org: John David Lamb (b. 1935)
  lafayette.debian.org: Eugenie Lafayette
  lebrun.debian.org: Francesca Lebrun (March 24th, 1756 - May 14th, 1791)
  lindberg.debian.org: Magnus Lindberg (June 27th, 1958)
  liszt.debian.org: Franz Liszt (October 22nd, 1811 - July 31st, 1886)
  locke.debian.org: Matthew Locke (ca. 1621 - 1677)
  lotti.debian.org: Antonio Lotti (ca. 1667 - January 5th, 1740)
  luchesi.debian.org: Andrea Luca Luchesi (May 23rd, 1741 - March 21st, 1801)
  mayer.debian.org: John Mayer (October 28th, 1930 - March 9th, 2004)
  mayr.debian.org: Johann(es) Simon Mayr (June 14th, 1763 - December 2nd, 1845)
  merikanto.debian.org: Oskar Merikanto (August 5th, 1868 - February 17th, 1924)
  merkel.debian.org: Gustav (Adolf) Merkel (November 12th, 1827 - October 30th, 1885)
  merulo.debian.org: Claudio Merulo (April 8th, 1533 - May 4th, 1604)
  morricone.debian.org: Ennio Morricone (November 10th, 1928 - )
  mundy.debian.org: William Mundy (c. 1529 - 1591)
  nielsen.debian.org: Carl August Nielsen (June 9th, 1865 - October 3rd, 1931)
  nono.debian.org: Luigi Nono (January 29, 1924 - May 8, 1990)
  orff.debian.org: Carl Orff (July 10th, 1895 - March 29th, 1982)
  paer.debian.org: Ferdinando Paër (July 1st, 1771 - May 3rd, 1839)
  paganini.debian.org: Niccolò Paganini (October 27th, 1782 - May 27th, 1840)
  penalosa.debian.org: Francisco de Peñalosa (c. 1470 - April 1st, 1528)
  pergolesi.debian.org: Giovanni Battista Pergolesi (January 4th, 1710 - March 16th or 17th, 1736)
  peri.debian.org: Jacopo Peri (August 20th, 1561 - August 12th, 1633)
  pescetti.debian.org: Giovanni Battista Pescetti (ca. 1704  - 1766)
  pettersson.debian.org: Gustav Allan Pettersson (September 19th, 1911 - June 20th, 1980)
  piatti.debian.org: Carlo Alfredo Piatti (January 8th, 1822 - July 18th, 1901)
  porpora.debian.org: Niccolò (Antonio) Porpora (17 August 1686 - 3 March 1768)
  poulenc.debian.org: Francis Jean Marcel Poulenc (January 7, 1899 - January 30, 1963)
  powell.debian.org: Andrew Powell (b. April 18th, 1949)
  praetorius.debian.org: Hieronymus Praetorius (August 10th, 1560 - January 27th, 1629)
  quantz.debian.org: Johann Joachim Quantz (January 30th, 1697 - July 12th, 1773)
  raff.debian.org: Joseph Joachim Raff (May 27th, 1822 - June 24th or 25th, 1882)
  rautavaara.debian.org: Einojuhani Rautavaara (born October 9th, 1928)
  ravel.debian.org: Joseph-Maurice Ravel (March 7th, 1875 - December 28th, 1937)
  respighi.debian.org: Ottorino Respighi (July 9th, 1879 - April 18th, 1936)
  reger.debian.org: Johann Baptist Joseph Maximilian Reger (March 19, 1873 - May 11th, 1916)
  ries.debian.org: Franz Ries (April 7th, 1846 - January 20th, 1932)
  rietz.debian.org: August Wilhelm Julius Rietz (December 28th, 1812 - September 12th, 1877)
  rore.debian.org: Cipriano de Rore (occasionally Cypriano) (1515 or 1516 - between September 11 and September 20, 1565)
  rossini.debian.org: Gioachino Rossini (February 29th, 1792 - November 13th, 1868)
  saens.debian.org: Charles-Camille Saint-Saëns  (October 9th, 1835 - December 16th, 1921)
  salieri.debian.org: Antonio Salieri (August 18th, 1750 - May 7th, 1825)
  samosa.debian.org: The samosa is a stuffed pastry and a popular snack in South Asia, Southeast Asia, Central Asia, the Arabian Peninsula, throughout the Mediterranean (Greece), Southwest Asia, the Horn of Africa and North Africa.
  santoro.debian.org: Cláudio Santoro (November 23rd, 1919 - March 27th, 1989)
  scelsi.debian.org: Giacinto Scelsi (January 8th, 1905 - August 9th, 1988)
  schein.debian.org: Johann Hermann Schein (January 20th, 1586 - November 19th, 1630)
  schroeder.debian.org: Hermann Schroeder (March 26th, 1904 - October 7th, 1984)
  schumann.debian.org: Robert Alexander Schumann (June 8th, 1810 - July 29th, 1856)
  schuetz.debian.org: Heinrich Schütz (October 8th, 1585 - November 6th, 1672)
  senfl.debian.org: Ludwig Senfl (~1490 - ~1543)
  sibelius.debian.org: Jean Sibelius (December 8th, 1865 - September 20th, 1957)
  smetana.debian.org: Bedřich Smetana (March 2nd, 1824 - May 12th, 1884)
  soler.debian.org: Padre Antonio Soler (December 3rd, 1729 (baptized) - December 20th, 1783)
  sperger.debian.org: Johannes Matthias Sperger (March 23th, 1750 - May 13th, 1812)
  spohr.debian.org: Louis Spohr (April 5th, 1784 - October 22nd, 1859)
  spontini.debian.org: Gaspare Luigi Pacifico Spontini (November 14th, 1774 - January 24th, 1851)
  stabile.debian.org: Annibale Stabile (~1535 - April 1595)
  steffani.debian.org: Agostino Steffani (July 25th, 1653 - February 12th, 1728)
  tartini.debian.org: Giuseppe Tartini (April 8th, 1692 - February 26th, 1770)
  tchaikovsky.debian.org: Pyotr Ilyich Tchaikovsky (Пётр Ильич Чайковский) (May 7th, 1840 - November 6th, 1893)
  traetta.debian.org: Tommaso Michele Francesco Saverio Traetta (March 30th, 1727 - April 6th, 1779)
  unger.debian.org: Caroline Unger (October 28th, 1803 - March 23th, 1877)
  valente.debian.org: Vincenzo Valente (February 21st, 1855 - September 6th, 1921)
  vitry.debian.org: Philippe de Vitry (October 31st, 1291 - June 9th, 1361)
  vivaldi.debian.org: Antonio Lucio Vivaldi (March 4th, 1678 - July 28th, 1741)
  voltaire.debian.org: François-Marie Arouet (Voltaire) (November 21st, 1694 - May 30th, 1778)
  widor.debian.org: Charles-Marie Jean Albert Widor (February 21st, 1844 - March 12th, 1937)
  wieck.debian.org: Clara Josephine Wieck (September 13th, 1819 - May 20th, 1896)
  wolkenstein.debian.org: Oswald von Wolkenstein (1377 - August 2nd, 1445)
  zandonai.debian.org: Riccardo Zandonai (May 30th, 1883 - June 5th, 1944)
  zelenka.debian.org: Jan Dismas Zelenka (October 16th, 1679 - December 23rd, 1745)
footer:
  zandonai.debian.org: "Debian s390 buildd system kindly provided by Zentrum fuer Informationsverarbeitung und Informationstechnik [zivit]"
  zelenka.debian.org: "Debian s390 porter system kindly provided by Zentrum fuer Informationsverarbeitung und Informationstechnik [zivit]"
services:
  bugsmaster:
  bugsmx:
    - busoni.debian.org
  dbmaster:
    - draghi.debian.org
  mailrelay:
    - kokkonen.debian.org
    - merikanto.debian.org
  muninmaster: spohr.debian.org
  nagiosmaster: tchaikovsky.debian.org
  extranrpeclient:
    - orff.debian.org
  packagesmaster: powell.debian.org
  packagesqamaster: master.debian.org
  puppetmaster: handel.debian.org
  qamaster: merkel.debian.org
  rtmaster: 
    - reger.debian.org
host_settings:
  heavy_exim:
    - bellini.debian.org
    - busoni.debian.org
    - chopin.debian.org
    - draghi.debian.org
    - franck.debian.org
    - grieg.debian.org
    - klecker.debian.org
    - kokkonen.debian.org
    - master.debian.org
    - merikanto.debian.org
    - merkel.debian.org
    - morricone.debian.org
    - nono.debian.org
    - powell.debian.org
    - quantz.debian.org
    - ravel.debian.org
    - reger.debian.org
    - spohr.debian.org
    - valente.debian.org
  apache2_security_mirror:
    - gluck.debian.org
    - lobos.debian.org
    - saens.debian.org
    - santoro.debian.org
    - schein.debian.org
    - steffani.debian.org
    - villa.debian.org
    - wieck.debian.org
  apache2_www_mirror:
    - bellini.debian.org
    - englund.debian.org
    - gluck.debian.org
    - klecker.debian.org
    - kokkonen.debian.org
    - senfl.debian.org
    - santoro.debian.org
    - wolkenstein.debian.org
  timeserver:
    - merikanto.debian.org
    - orff.debian.org
    - ravel.debian.org
    - busoni.debian.org
  buildd:
    - alain.debian.org
    - alkman.debian.org
    - alwyn.debian.org
    - ancina.debian.org
    - antheil.debian.org
    - arcadelt.debian.org
    - argento.debian.org
    - arnold.debian.org
    - ball.debian.org
    - barber.debian.org
    - biber.debian.org
    - brahms.debian.org
    - caballero.debian.org
    - corelli.debian.org
    - fano.debian.org
    - fasch.debian.org
    - field.debian.org
    - finzi.debian.org
    - goedel.debian.org
    - goetz.debian.org
    - krenek.debian.org
    - lafayette.debian.org
    - lebrun.debian.org
    - lucatelli.debian.org
    - malo.debian.org
    - mayer.debian.org
    - mayr.debian.org
    - mundy.debian.org
    - murphy.debian.org
    - penalosa.debian.org
    - peri.debian.org
    - porpora.debian.org
    - poulenc.debian.org
    - praetorius.debian.org
    - rem.debian.org
    - schroeder.debian.org
    - spontini.debian.org
    - vitry.debian.org
    - voltaire.debian.org
    - zandonai.debian.org
  squeeze:
    - arne.debian.org
    - beethoven.debian.org
    - byrd.debian.org
    - cilea.debian.org
    - danzi.debian.org
    - duarte.debian.org
    - fano.debian.org
    - fasch.debian.org
    - field.debian.org
    - finzi.debian.org
    - geo1.debian.org
    - heininen.debian.org
    - kassia.debian.org
    - kaufmann.debian.org
    - lamb.debian.org
    - lindberg.debian.org
    - locke.debian.org
    - lotti.debian.org
    - merikanto.debian.org
    - murphy.debian.org
    - nono.debian.org
    - piatti.debian.org
    - quantz.debian.org
    - raff.debian.org
    - rautavaara.debian.org
    - reger.debian.org
    - rem.debian.org
    - rietz.debian.org
    - rossini.debian.org
    - salieri.debian.org
    - santoro.debian.org
    - scelsi.debian.org
    - schuetz.debian.org
    - sibelius.debian.org
    - spohr.debian.org
    - tchaikovsky.debian.org
    - traetta.debian.org
    - unger.debian.org
    - wieck.debian.org
  smarthost:
    abel.debian.org: mailout.debian.org
    agnesi.debian.org: mailout.debian.org
    agricola.debian.org: mailout.debian.org
    alain.debian.org: mailout.debian.org
    albeniz.debian.org: mailout.debian.org
    alkman.debian.org: mailout.debian.org
    alwyn.debian.org: mailout.debian.org
    ancina.debian.org: mailout.debian.org
    antheil.debian.org: mailout.debian.org
    arcadelt.debian.org: mailout.debian.org
    argento.debian.org: mailout.debian.org
    arne.debian.org: mailout.debian.org
    arnold.debian.org: mailout.debian.org
    ball.debian.org: mailout.debian.org
    barber.debian.org: mailout.debian.org
    beethoven.debian.org: mailout.debian.org
    biber.debian.org: mailout.debian.org
    brahms.debian.org: mailout.debian.org
    byrd.debian.org: mailout.debian.org
    caballero.debian.org: mailout.debian.org
    cilea.debian.org: mailout.debian.org
    corelli.debian.org: mailout.debian.org
    crest.debian.org: mailout.debian.org
    danzi.debian.org: mailout.debian.org
    dijkstra.debian.org: mailout.debian.org
    duarte.debian.org: mailout.debian.org
    englund.debian.org: mailout.debian.org
    escher.debian.org: mailout.debian.org
    fano.debian.org: mailout.debian.org
    fasch.debian.org: mailout.debian.org
    field.debian.org: mailout.debian.org
    finzi.debian.org: mailout.debian.org
    gabrielli.debian.org: mailout.debian.org
    geo1.debian.org: mailout.debian.org
    geo2.debian.org: mailout.debian.org
    geo3.debian.org: mailout.debian.org
    gluck.debian.org: mailout.debian.org
    goedel.debian.org: mailout.debian.org
    goetz.debian.org: mailout.debian.org
    handel.debian.org: mailout.debian.org
    heininen.debian.org: mailout.debian.org
    holter.debian.org: mailout.debian.org
    kassia.debian.org: mailout.debian.org
    kaufmann.debian.org: mailout.debian.org
    krenek.debian.org: mailout.debian.org
    lamb.debian.org: mailout.debian.org
    lafayette.debian.org: mailout.debian.org
    lebrun.debian.org: mailout.debian.org
    leisner.debian.org: mailout.debian.org
    lindberg.debian.org: mailout.debian.org
    lobos.debian.org: mailout.debian.org
    locke.debian.org: mailout.debian.org
    lotti.debian.org: mailout.debian.org
    lucatelli.debian.org: mailout.debian.org
    luchesi.debian.org: mailout.debian.org
    malo.debian.org: mailout.debian.org
    mayer.debian.org: mailout.debian.org
    mayr.debian.org: mailout.debian.org
    merulo.debian.org: mailout.debian.org
    mundy.debian.org: mailout.debian.org
    murphy.debian.org: mailout.debian.org
    nielsen.debian.org: mailout.debian.org
    orff.debian.org: mailout.debian.org
    paer.debian.org: mailout.debian.org
    paganini.debian.org: mailout.debian.org
    penalosa.debian.org: mailout.debian.org
    pergolesi.debian.org: mailout.debian.org
    peri.debian.org: mailout.debian.org
    pescetti.debian.org: mailout.debian.org
    pettersson.debian.org: mailout.debian.org
    piatti.debian.org: mailout.debian.org
    porpora.debian.org: mailout.debian.org
    poulenc.debian.org: mailout.debian.org
    praetorius.debian.org: mailout.debian.org
    raff.debian.org: mailout.debian.org
    rautavaara.debian.org: mailout.debian.org
    rem.debian.org: mailout.debian.org
    respighi.debian.org: mailout.debian.org
    ries.debian.org: mailout.debian.org
    rietz.debian.org: mailout.debian.org
    rore.debian.org: mailout.debian.org
    rossini.debian.org: mailout.debian.org
    saens.debian.org: mailout.debian.org
    salieri.debian.org: mailout.debian.org
    santoro.debian.org: mailout.debian.org
    scelsi.debian.org: mailout.debian.org
    schein.debian.org: mailout.debian.org
    schroeder.debian.org: mailout.debian.org
    schumann.debian.org: mailout.debian.org
    schuetz.debian.org: mailout.debian.org
    senfl.debian.org: mailout.debian.org
    sibelius.debian.org: mailout.debian.org
    smetana.debian.org: mailout.debian.org
    soler.debian.org: mailout.debian.org
    sperger.debian.org: mailout.debian.org
    spontini.debian.org: mailout.debian.org
    stabile.debian.org: mailout.debian.org
    steffani.debian.org: mailout.debian.org
    tchaikovsky.debian.org: mailout.debian.org
    traetta.debian.org: mailout.debian.org
    unger.debian.org: mailout.debian.org
    villa.debian.org: mailout.debian.org
    vitry.debian.org: mailout.debian.org
    vivaldi.debian.org: mailout.debian.org
    voltaire.debian.org: mailout.debian.org
    widor.debian.org: mailout.debian.org
    wieck.debian.org: mailout.debian.org
    zandonai.debian.org: mailout.debian.org
    zee.debian.org: mailout.debian.org
    zelenka.debian.org: mailout.debian.org
  mail_port:
    ancina.debian.org: 2025
    kassia.debian.org: 587
    piatti.debian.org: 2025
  no_munin:
    - agnesi.debian.org
    - allegri.debian.org
    - escher.debian.org
    - fano.debian.org
    - malo.debian.org
  entropy_key:
    - heininen.debian.org
    - englund.debian.org
    - rautavaara.debian.org
    - salieri.debian.org
#  reservedaddrs:
#    ball.debian.org: "0.0.0.0/8 : 127.0.0.0/8 : 169.254.0.0/16 : 172.16.0.0/12 : 192.0.0.0/17 : 192.168.0.0/16 : 224.0.0.0/4 : 240.0.0.0/5 : 248.0.0.0/5"
---

